Remove action-based logic with intent-based logic
watsonwork/watsonwork-weather pull request #2
Opened 2017-05-10 19:32 UTC by CyrusJia

Remove onActionNextStep() from app.js and events.js

Modify onAction to onIntent and adjust corresponding logic

2017-05-15 18:14 UTC, jsdelfino commented on README.md
> +# watsonwork-weather-intent-based
We're not changing the name of this project are we?

2017-05-15 18:16 UTC, jsdelfino commented on src/events.js
> +    // Retrieve the annotated message
Not sure why the formatting changes here (we've been using spaces for indentation, is this a tab?)

2017-05-15 18:16 UTC, CyrusJia commented on README.md
> +# watsonwork-weather-intent-based
Would it make sense to separate this project into two different repos: one for action responses and one for intent responses?

2017-05-15 18:16 UTC, jsdelfino commented on src/events.js
> +    if (message.createdBy.id === appId)
Conflicts with the current coding style of this example app (no space between if and ()

2017-05-15 18:17 UTC, jsdelfino commented on src/events.js
> +        // Return the extracted info, annotation, annotated message
Looks like another unnecessary formatting change (more of these in this pull request)

2017-05-15 18:17 UTC, jsdelfino commented on src/events.js
> +  log(evt);
Would be good to have a log message too here

2017-05-15 18:20 UTC, jsdelfino commented on src/app.js
>  // A sample app that listens to messages posted to a space in IBM
Many many changes here probably caused by your editor. Can you please re-apply the minimum set of changes that will do what you intended to do? and I'll be happy to review again :) Thanks!

2017-05-15 18:22 UTC, CyrusJia commented on src/app.js
>  // A sample app that listens to messages posted to a space in IBM
Sure, no problem!

2017-05-16 21:32 UTC, jsdelfino commented on src/app.js
> +    // Handle messages identified as intent requests
I'd suggest to rephrase as something like 'messages on which an intent has been recognized'

2017-05-16 21:35 UTC, jsdelfino commented on src/app.js
> +    // Handle messages identified as intent requests
or 'identified' in place of 'recognized'

2017-05-16 21:36 UTC, jsdelfino commented on src/app.js
> +            else if(intent == 'forecast')
I'm surprised that Lint didn't pick that up, but I'd suggest to change == to ===

2017-05-16 21:40 UTC, jsdelfino requested changes
Looks pretty good to me, I added a few comments for some minor issues.

Can you convert it to a pull request with a single clean commit containing an overview of the change that's implemented here?

Also I'm guessing that you didn't mean to push your .DS_Store file :)

With these minor changes I'll be +1 on merging this pull request. Thanks again for your contribution!!

2017-05-18 14:16 UTC, jsdelfino commented
Thanks for this contribution!

Closing this pull request as the code changes have now been integrated in pull request #4.

2017-05-18 14:16 UTC, closed without merging